name: terraform

on:
  push:
    branches:
      - "main"

env:
  TF_CLOUD_ORGANIZATION: "github-action-tf"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "git-cicd-tf"
  CONFIG_DIRECTORY: "./"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      
      - name: Initialize Terraform
        id: init
        run: terraform init -input=false 

      - name: Plan Terraform
        id: plan
        run: terraform plan -input=false 
