name: terraform

on:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    env:
      REGION_ID: "ap-southeast-1"
      access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
      access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      
      - name: Initialize Terraform
        id: init
        run: terraform init -input=false 

      - name: Plan Terraform
        id: plan
        run: terraform plan -input=false 
        env:
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
