name: terraform

on:
  push:
    branches:
      - "main"
      
#env:
  #REGION_ID: "ap-southeast-1"
  #access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
  #access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      
      - name: Initialize Terraform
        id: init
        env:
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
          run: terraform init -input=false 
